import time
personalinfo = input("what is your pin for your bank card?")
personalinfo2 = input("What is your card number?")
print("Verifying card number...")
print(".")
time.sleep(0.20)
print("..")
time.sleep(0.20)
print("...")
time.sleep(0.20)
print(".")
time.sleep(0.20)
print("..")
time.sleep(0.20)
print("...")
time.sleep(0.20)
print("Contacting Servers...")
time.sleep(0.20)
print(".")
time.sleep(0.20)
print("..")
time.sleep(0.20)
print("...")
time.sleep(0.20)
print(".")
time.sleep(0.20)
print("..")
time.sleep(0.20)
print("...")
time.sleep(0.20)
print("Please confirm that your pin is ", personalinfo, "and your card number is ", personalinfo2, ". (type yes or no)")
confirm = input("yes/no")
if confirm == ("yes"):
    print("Logging into account...")
    time.sleep(0.20)
    print(".")
    time.sleep(0.20)
    print("..")
    time.sleep(0.20)
    print("...")
    time.sleep(0.20)
    print(".")
    time.sleep(0.20)
    print("..")
    time.sleep(0.20)
    print("...")
    time.sleep(0.20)
    print("Thank you for your money! :D")
else:
    print("please restart this script")
